# -*- coding: utf-8 -*-

from PySide6.QtCore import (QCoreApplication, QMetaObject, QSize)
from PySide6.QtWidgets import (QComboBox, QHBoxLayout, QLabel, QPushButton, QRadioButton, QTextEdit, QGridLayout)


class Ui_YoyoOCR(object):
    def setupUi(self, main):
        if not main.objectName():
            main.setObjectName(u"main")
        main.resize(800, 400)
        self.gridLayout = QGridLayout(main)
        self.gridLayout.setObjectName(u"gridLayout")
        self.titleHorizontalLayout = QHBoxLayout()
        self.titleHorizontalLayout.setObjectName(u"titleHorizontalLayout")
        self.languageTab = QHBoxLayout()
        self.languageTab.setSpacing(6)
        self.languageTab.setObjectName(u"languageTab")
        self.languageTab.setContentsMargins(0, -1, 50, -1)
        self.languageLabel = QLabel(main)
        self.languageLabel.setObjectName(u"languageLabel")
        self.languageTab.addWidget(self.languageLabel)
        self.languageComboBox = QComboBox(main)
        self.languageComboBox.setObjectName(u"languageComboBox")
        self.languageComboBox.setSizeIncrement(QSize(0, 0))
        self.languageComboBox.setBaseSize(QSize(0, 0))
        self.languageTab.addWidget(self.languageComboBox)
        self.titleHorizontalLayout.addLayout(self.languageTab)
        self.functionTab = QHBoxLayout()
        self.functionTab.setObjectName(u"functionTab")
        self.functionTab.setContentsMargins(30, -1, 30, -1)
        self.functionLabel = QLabel(main)
        self.functionLabel.setObjectName(u"functionLabel")
        self.functionTab.addWidget(self.functionLabel)
        self.ocrRadioButton = QRadioButton(main)
        self.ocrRadioButton.setObjectName(u"ocrRadioButton")
        self.functionTab.addWidget(self.ocrRadioButton)
        self.translateRadioButton = QRadioButton(main)
        self.translateRadioButton.setObjectName(u"translateRadioButton")
        self.functionTab.addWidget(self.translateRadioButton)
        self.translateRadioButton.setChecked(True)
        self.voiceRadioButton = QRadioButton(main)
        self.voiceRadioButton.setObjectName(u"voiceRadioButton")
        self.functionTab.addWidget(self.voiceRadioButton)
        self.titleHorizontalLayout.addLayout(self.functionTab)
        self.pushButton = QPushButton(main)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(True)
        self.pushButton.setAutoRepeatDelay(300)
        self.titleHorizontalLayout.addWidget(self.pushButton)
        self.titleHorizontalLayout.setStretch(0, 2)
        self.titleHorizontalLayout.setStretch(1, 4)
        self.titleHorizontalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.titleHorizontalLayout, 0, 0, 1, 1)
        self.textHorizontalLayout = QHBoxLayout()
        self.textHorizontalLayout.setSpacing(0)
        self.textHorizontalLayout.setObjectName(u"textHorizontalLayout")
        self.input = QTextEdit(main)
        self.input.setObjectName(u"input")
        self.textHorizontalLayout.addWidget(self.input)
        self.output = QTextEdit(main)
        self.output.setObjectName(u"output")
        self.textHorizontalLayout.addWidget(self.output)
        self.gridLayout.addLayout(self.textHorizontalLayout, 1, 0, 1, 1)
        self.retranslateUi(main)
        QMetaObject.connectSlotsByName(main)


    def retranslateUi(self, main):
        main.setWindowTitle(QCoreApplication.translate("main", u"OCR识别翻译工具", None))
        self.languageLabel.setText(QCoreApplication.translate("main", u"1.目标语言", None))
        self.functionLabel.setText(QCoreApplication.translate("main", u"2.功能选型", None))
        self.ocrRadioButton.setText(QCoreApplication.translate("main", u"OCR识别", None))
        self.translateRadioButton.setText(QCoreApplication.translate("main", u"文本翻译", None))
        self.voiceRadioButton.setText(QCoreApplication.translate("main", u"语音朗读", None))
        self.pushButton.setText(QCoreApplication.translate("main", u"开始", None))

        # 语言下拉框内容
        self.languageComboBox.addItem("中文简体")
        self.languageComboBox.addItem("中文繁体")
        self.languageComboBox.addItem("英语")
        self.languageComboBox.addItem("日语")
        self.languageComboBox.addItem("韩语")
        self.languageComboBox.addItem("德语")
        self.languageComboBox.addItem("法语")
        self.languageComboBox.addItem("西班牙语")
        self.languageComboBox.addItem("意大利语")
        self.languageComboBox.addItem("俄语")

        # 设置默认值
        self.languageComboBox.setCurrentIndex(2)
        self.languageComboBox.currentText()

